name: karsajobs
on:
  push:
    branches:
      - karsajobs
jobs:
  karsajobs-ci:
    name: Checkout-Lint-Test-Build-Push
    environment: karsajobs-prod
    runs-on: ubuntu:latest
    steps:
      - name: Running checkout repo
        uses: actions/checkout@v4
      - name: Running lint Dockerfile
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: "Dockerfile"
      - name: Running unit test
        run: go test -v -short --count=1 $(go list ./...)
      - name: Running build and push Docker Image
        env:
          GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}
        run: |
          export GHCR_TOKEN=$GHCR_TOKEN
          bash ./build_push_image_karsajobs.sh
